/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkflowsRouteImport } from './routes/api/workflows'
import { Route as ApiSkillRouteImport } from './routes/api/skill'
import { Route as ApiModelRouteImport } from './routes/api/model'
import { Route as ApiExecuteLarkRouteImport } from './routes/api/execute/lark'
import { Route as ApiExecuteCodeRouteImport } from './routes/api/execute/code'
import { Route as ApiExecuteBmadRouteImport } from './routes/api/execute/bmad'
import { Route as ApiExecuteAgentRouteImport } from './routes/api/execute/agent'
import { Route as ApiBmadAgentsRouteImport } from './routes/api/bmad/agents'

const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsRoute = ApiWorkflowsRouteImport.update({
  id: '/api/workflows',
  path: '/api/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillRoute = ApiSkillRouteImport.update({
  id: '/api/skill',
  path: '/api/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelRoute = ApiModelRouteImport.update({
  id: '/api/model',
  path: '/api/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteLarkRoute = ApiExecuteLarkRouteImport.update({
  id: '/api/execute/lark',
  path: '/api/execute/lark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteCodeRoute = ApiExecuteCodeRouteImport.update({
  id: '/api/execute/code',
  path: '/api/execute/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteBmadRoute = ApiExecuteBmadRouteImport.update({
  id: '/api/execute/bmad',
  path: '/api/execute/bmad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteAgentRoute = ApiExecuteAgentRouteImport.update({
  id: '/api/execute/agent',
  path: '/api/execute/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBmadAgentsRoute = ApiBmadAgentsRouteImport.update({
  id: '/api/bmad/agents',
  path: '/api/bmad/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/api/model': typeof ApiModelRoute
  '/api/skill': typeof ApiSkillRoute
  '/api/workflows': typeof ApiWorkflowsRoute
  '/api/bmad/agents': typeof ApiBmadAgentsRoute
  '/api/execute/agent': typeof ApiExecuteAgentRoute
  '/api/execute/bmad': typeof ApiExecuteBmadRoute
  '/api/execute/code': typeof ApiExecuteCodeRoute
  '/api/execute/lark': typeof ApiExecuteLarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/api/model': typeof ApiModelRoute
  '/api/skill': typeof ApiSkillRoute
  '/api/workflows': typeof ApiWorkflowsRoute
  '/api/bmad/agents': typeof ApiBmadAgentsRoute
  '/api/execute/agent': typeof ApiExecuteAgentRoute
  '/api/execute/bmad': typeof ApiExecuteBmadRoute
  '/api/execute/code': typeof ApiExecuteCodeRoute
  '/api/execute/lark': typeof ApiExecuteLarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/api/model': typeof ApiModelRoute
  '/api/skill': typeof ApiSkillRoute
  '/api/workflows': typeof ApiWorkflowsRoute
  '/api/bmad/agents': typeof ApiBmadAgentsRoute
  '/api/execute/agent': typeof ApiExecuteAgentRoute
  '/api/execute/bmad': typeof ApiExecuteBmadRoute
  '/api/execute/code': typeof ApiExecuteCodeRoute
  '/api/execute/lark': typeof ApiExecuteLarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/models'
    | '/api/model'
    | '/api/skill'
    | '/api/workflows'
    | '/api/bmad/agents'
    | '/api/execute/agent'
    | '/api/execute/bmad'
    | '/api/execute/code'
    | '/api/execute/lark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models'
    | '/api/model'
    | '/api/skill'
    | '/api/workflows'
    | '/api/bmad/agents'
    | '/api/execute/agent'
    | '/api/execute/bmad'
    | '/api/execute/code'
    | '/api/execute/lark'
  id:
    | '__root__'
    | '/'
    | '/models'
    | '/api/model'
    | '/api/skill'
    | '/api/workflows'
    | '/api/bmad/agents'
    | '/api/execute/agent'
    | '/api/execute/bmad'
    | '/api/execute/code'
    | '/api/execute/lark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelsRoute: typeof ModelsRoute
  ApiModelRoute: typeof ApiModelRoute
  ApiSkillRoute: typeof ApiSkillRoute
  ApiWorkflowsRoute: typeof ApiWorkflowsRoute
  ApiBmadAgentsRoute: typeof ApiBmadAgentsRoute
  ApiExecuteAgentRoute: typeof ApiExecuteAgentRoute
  ApiExecuteBmadRoute: typeof ApiExecuteBmadRoute
  ApiExecuteCodeRoute: typeof ApiExecuteCodeRoute
  ApiExecuteLarkRoute: typeof ApiExecuteLarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows': {
      id: '/api/workflows'
      path: '/api/workflows'
      fullPath: '/api/workflows'
      preLoaderRoute: typeof ApiWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skill': {
      id: '/api/skill'
      path: '/api/skill'
      fullPath: '/api/skill'
      preLoaderRoute: typeof ApiSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model': {
      id: '/api/model'
      path: '/api/model'
      fullPath: '/api/model'
      preLoaderRoute: typeof ApiModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute/lark': {
      id: '/api/execute/lark'
      path: '/api/execute/lark'
      fullPath: '/api/execute/lark'
      preLoaderRoute: typeof ApiExecuteLarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute/code': {
      id: '/api/execute/code'
      path: '/api/execute/code'
      fullPath: '/api/execute/code'
      preLoaderRoute: typeof ApiExecuteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute/bmad': {
      id: '/api/execute/bmad'
      path: '/api/execute/bmad'
      fullPath: '/api/execute/bmad'
      preLoaderRoute: typeof ApiExecuteBmadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute/agent': {
      id: '/api/execute/agent'
      path: '/api/execute/agent'
      fullPath: '/api/execute/agent'
      preLoaderRoute: typeof ApiExecuteAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bmad/agents': {
      id: '/api/bmad/agents'
      path: '/api/bmad/agents'
      fullPath: '/api/bmad/agents'
      preLoaderRoute: typeof ApiBmadAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelsRoute: ModelsRoute,
  ApiModelRoute: ApiModelRoute,
  ApiSkillRoute: ApiSkillRoute,
  ApiWorkflowsRoute: ApiWorkflowsRoute,
  ApiBmadAgentsRoute: ApiBmadAgentsRoute,
  ApiExecuteAgentRoute: ApiExecuteAgentRoute,
  ApiExecuteBmadRoute: ApiExecuteBmadRoute,
  ApiExecuteCodeRoute: ApiExecuteCodeRoute,
  ApiExecuteLarkRoute: ApiExecuteLarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
